### ISSUE TITLE
[Ulduar] Kologarn: Overhead Smash should be avoidable

### ISSUE THREAD

**Issue by oneadanut** [Stormforge-gg/Frostmourne-bugtracker#301]
The ability Overhead Smash from Kologarn is applying the debuff every cd without tanks avoiding any of them.

https://www.wowhead.com/spell=64003/overhead-smash#comments

There was a fix on Whitemane that didn't fix the issue. https://github.com/gamefreedomgit/Frostmourne/issues/2015

**Comment by oneadanut** [comment]
Reseting the boss by going out from the room, makes him auto-pull on respawn several times until he calms down.

**Comment by Wolffenstein** [comment]
It may have been avoidable when Ulduar first launched but it's clear Blizzard added the 'always hits' parameter to it later, probably in one of the hotfixes. I'm not going to change that

**Comment by oneadanut** [comment]
> It may have been avoidable when Ulduar first launched but it's clear Blizzard added the 'always hits' parameter to it later, probably in one of the hotfixes. I'm not going to change that

Where is the proof of that? Every classic video shows that tanks are not getting constant stacks of the debuff meaning they are avoiding some of them. Also, every guide says so.

**Comment by oneadanut** [comment]
https://youtu.be/mYVbxPrXhsQ

In this video, the dk tanked boss whole fight and he got only 2 stacks. He even lost the stacks in the end, meaning 45s without any reapply.

**Comment by oneadanut** [comment]
Perhaps you are reffering to https://www.wowhead.com/wotlk/spell=64710/overhead-smash-tremor which probably should be casted on every cd, but the report is about the Crunch armor debuff applied from Overhead Smash/One-armed Overhead Smash which should be avoidable.

**Comment by Wolffenstein** [comment]
No, I'm not. That's just the AoE damage/interrupt triggered directly by Overhead Smash

Overhead Smash cannot be avoided, even on the video you've linked every time it's actually casted by Kologarn it hits. We also checked classic logs and it was the same there - every Overhead Smash cast was a hit.

The reason why it's applied less often on classic/retail is due to how Kologarn's AI works there. Spell data shows that all arm attacks (Grip, Smash, Shockwave) share the same spell category with each of them applying a cooldown when casted - Shockwave applies a 10s cd to the entire category, Stone Grip 8s and Smash 4s. What happens is after the first ~10s (and then roughly every 2s) Kologarn attempts to cast one of the spells from that category (at random from what I've been able to assess), then depending on which spell is used the specific cooldown is applied and then another attempt is made once that cooldown passes (the same arm ability cannot be used twice in a row). Since the spells depend on which arm is available, this means that Kologarn can alternate between the same two attacks if both arms are alive as there are three possible spells to choose from. This means the following can occur (0-2s buffer for AI attack roll timer):
0s - encounter starts
~10s - Shockwave
~22s - Stone Grip
~32s - Shockwave
~44s - Stone Grip
~54s - Shockwave
etc., which makes the Overhead Smash simply not occur. There is no dodge/parry, the ability just didn't happen. This can lead to stacks dropping entirely or being reapplied at the last possible second when both arms are up. It's especially egregious on Classic videos/logs since he dies in like 2 minutes tops, leading to only a few Smash casts. Even on the video you've linked you can see that once the first Arm gets killed the Smashes occur more frequently.

I have rewritten this portion of the encounter and if you try it on PTR you should find it matches the Classic/Retail version a lot more closely.

**Comment by oneadanut** [comment]
As long he doesn't spam the debuff on tanks, it's more than fine. My issue was that on last server, people had to use 3 tanks because of this. Thank you for the fix.

**Comment by oneadanut** [comment]
He is kinda broken right now https://streamable.com/8y98g7 probably because of "Kologarn will no longer aggro by himself and will now wait for players to start attacking him"
Also, in the end of the video, he did the 3rd stack of Crunch Armor  while being away from him.

In 10hc, Crunch Armor should last 20s instead of 6s (pre-nerf value is 20s and post-nerf is 6s).
Also, he still had the respawn pull bug on 10 man.

**Comment by Godmatik** [comment]
Fixed - recheck on PTR

**Comment by oneadanut** [comment]
He seems fixed on 10hc on first pull, but switching on 10 normal he is still broken like in my previous video, If you switch back to heroic, he has the same behavior. Unless, you go out of the room and he gets fixed.
In 25 man is the same behavior, switching difficulty bugs him unless you go out of the room. Perhaps, add more invisible flags inside the room to activate him or make the invisible flag to auto-activate when switching difficulty.

The Crunch Armor duration is fixed in 10hc, but it should stack, Right now, it just refreshes the duration of the old one.
In 10 normal the duration should be 6 seconds.

Also, the hitbox of boss/arms is a bit too low. Looking to the pets in this video https://www.youtube.com/watch?v=KPiHpTl6lqc it seems hitbox should be larger, like on the edge of the square. Arms hitbox is too small right now, it seems they share the hitbox of the body and not separate hitboxes. If you look in the beginning of the video, people started attacking the right arm and meeles were far left. Here you can't attack it from that position.

**Comment by oneadanut** [comment]
> He seems fixed on 10hc on first pull, but switching on 10 normal he is still broken like in my previous video, If you switch back to heroic, he has the same behavior. Unless, you go out of the room and he gets fixed. In 25 man is the same behavior, switching difficulty bugs him unless you go out of the room. Perhaps, add more invisible flags inside the room to activate him or make the invisible flag to auto-activate when switching difficulty.
> 
> The Crunch Armor duration is fixed in 10hc, but it should stack, Right now, it just refreshes the duration of the old one. In 10 normal the duration should be 6 seconds.
> 
> Also, the hitbox of boss/arms is a bit too low. Looking to the pets in this video https://www.youtube.com/watch?v=KPiHpTl6lqc it seems hitbox should be larger, like on the edge of the square. Arms hitbox is too small right now, it seems they share the hitbox of the body and not separate hitboxes. If you look in the beginning of the video, people started attacking the right arm and meeles were far left. Here you can't attack it from that position.

Still not fixed.
https://streamable.com/gi5idc
