### ISSUE TITLE
[Ulduar] XT-002: Tympanic Tantrum not being mitigated with AoE reducing effects

### ISSUE THREAD

**Issue by oneadanut** [Stormforge-gg/Frostmourne-bugtracker#346]
Tympanic Tantrum should count as an AoE ability and Rogues should be able to mitigate the damage with Feint by 50%. Probably, it's the same issue with pets that should mitigate 90% damage and Feral druids with talent points in Predatory Instincts.

https://www.youtube.com/watch?v=qUnDw59KPfU

https://www.wowhead.com/wotlk/spell=62776/tympanic-tantrum#comments

**Comment by oneadanut** [comment]
Tympanic Tantrum shouldn't reset its cooldown if heart is killed. See in above video that Tympanic Tantrum happened instantly after heart was killed. The timer should just stop and continue if heart is killed or reset if heart was not killed.

Also, first Tympanic Tantrum should happen after 30-35s from pull, then on 1 min cd and it shouldn't cancel if pushed to heart phase during cast/channel.
https://youtu.be/fmS_Yyhj1HA

**Comment by oneadanut** [comment]
Tympanic Tantrum should count as physical damage and Hand of Protection should negate the damage. Other immunity effects such as Divine Shield / Iceblock, perhaps Detterence should negate the damage as well. Also, reducing damage effects such as Divine Sacrifice, Icebound fortitude, Divine protection, Barkskin, Shamanistic rage etc. should mitigate damage according to their tooltip, also talents that reduces damage taken or sanctuary buff/renewed hope. The only source that shouldnt mitigate the damage is armor.

Something broke since last fix on damage.

**Comment by Godmatik** [comment]
Fixed on PTR

**Comment by oneadanut** [comment]
> Tympanic Tantrum shouldn't reset its cooldown if heart is killed. See in above video that Tympanic Tantrum happened instantly after heart was killed. The timer should just stop and continue if heart is killed or reset if heart was not killed.
> 
> Also, first Tympanic Tantrum should happen after 30-35s from pull, then on 1 min cd and it shouldn't cancel if pushed to heart phase during cast/channel. https://youtu.be/fmS_Yyhj1HA

These are still not fixed.
https://www.wowhead.com/wotlk/news/beef-bar-world-first-yogg-0-and-algalon-kill-wotlk-classic-331061#news-post-331061 check on video 20:38 where he started Tantrum at 76%, then he didn't cancel cast/channel when pushed lower than 75%. Also, he did this Tantrum 40s after pull. Another video here https://www.youtube.com/watch?v=MF7Rqc-jTrw

Regarding the Tantrum timer reset https://www.youtube.com/watch?v=NJ-uq3E1O4s&t=81s

**Comment by oneadanut** [comment]
> Tympanic Tantrum should count as physical damage and Hand of Protection should negate the damage. Other immunity effects such as Divine Shield / Iceblock, perhaps Detterence should negate the damage as well. Also, reducing damage effects such as Divine Sacrifice, Icebound fortitude, Divine protection, Barkskin, Shamanistic rage etc. should mitigate damage according to their tooltip, also talents that reduces damage taken or sanctuary buff/renewed hope. The only source that shouldnt mitigate the damage is armor.
> 
> Something broke since last fix on damage.

This is partially fixed, immunity abilities work, but damage reduction abilities/buffs don't work: Divine Sacrifice, Divine protection, Glyph of Salvation, Glyph of Divine plea, Blessing of Sanctuary and talents like Improved Righteous fury and Improved Lay on Hands.

Probably it's the same issues for other classes buffs/abilities.
